game: "DCS World"
api: 1
steamID: 223750
uid: com.thegreatcabbage.dcs
author: TheGreatCabbage
packageName: "dcsworld"
features:
  - graphics

graphicsConfig: TODO

gameDirectory: "DCSWorld"
verificationPaths:
  - bin/DCS.exe
