game: "DCS World"
api: 1
steamID: 223750
uid: com.thegreatcabbage.dcs
author: TheGreatCabbage
packageName: "dcsworld"
features:
  - graphics
  - keymaps
  - saves

graphicsConfig:
  - C:\Users\$!USERNAME!$\Saved Games\DCS\Config\options.lua
  - C:\Users\$!USERNAME!$\Saved Games\DCS.OpenBeta\Config\options.lua
keymapConfig:
  - C:\Users\$!USERNAME!$\Saved Games\DCS\Config\Input
  - C:\Users\$!USERNAME!$\Saved Games\DCS.OpenBeta\Config\Input
savesFolder:
  - C:\Users\$!USERNAME!$\Saved Games\DCS\Missions\Campaigns
  - C:\Users\$!USERNAME!$\Saved Games\DCS.OpenBeta\Missions\Campaigns

gameDirectory: "DCSWorld"
verificationPaths:
  - bin/DCS.exe
